/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vfhehvbroksqiebyjbjt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmaGVodmJyb2tzcWllYnlqYmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU3NTkyMDksImV4cCI6MjA4MTMzNTIwOX0.Pmo8JPXReT-vpNY0INq5BJQVov2PNICF7WWq-gd2VcU"